testmigration::ConcourseCore:
  secrettest: '[SECRET-FROM-REPOSECRET:TESTMIGRATION__CONCOURSECORE__SECRETTEST]'
  test1: new value
  LD_API_AUTH_TOKEN: '[SECRET-FROM-REPOSECRET:TESTMIGRATION__CONCOURSECORE__LD_API_AUTH_TOKEN]'
  APPVERSION: '[SECRET-FROM-REPOSECRET:TESTMIGRATION__CONCOURSECORE__APPVERSION]'
