# File: scan-netsparker.yaml
trigger:
- main

pool:
  name: 'dds-concourse-ubuntu2004-01'
  workspace:
    clean: all

parameters:
- name: ENVIRONMENT
  displayName: ENVIRONMENT
  type: string
  default: us-int
  values:
    - us-dev
    - us-qa
    - us-perf
    - us-int
    - us-stage
    - eu-stage
- name: cfg
  type: object
  default:
    endpoint: $(NETSPARKER_MS_ENDPOINT)
    scanWebSitesProfile: $(NETSPARKER_MS_PROFILE_ID)
    scanWebSites: $(NETSPARKER_MS_WEBSITE_ID)
    jobOptions:
      timeoutInMinutes: 480
    autoDownload: true
- name: ctx
  type: object
  default: 
   name: "netsparker"
   displayName: "netspartkerjob"
 
variables:
- group: infra-devops-secrets
- group: ConcourseCore 
- group: ${{ parameters.ENVIRONMENT }}
- name: 'ENVIRONMENT'
  value: ${{ parameters.ENVIRONMENT }}
jobs:
- template: ../../DAST Scanner/DAST Scanner/scan-netsparker.yaml
  parameters:
    cfg: ${{ parameters.cfg }}
    ctx: ${{ parameters.ctx }}

# schedules:
# - cron: "0 22 * * *"
#   displayName: Daily DAST Scan
#   branches:
#     include:
#     - main
#   always: true