# Simple single-stage pipeline

trigger: none

stages:
- stage: Build
  displayName: 'Single Stage'
  jobs:
  - job: HelloWorld
    displayName: 'Hello World Job'
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: echo Hello, world!
      displayName: 'Run hello world script'
