# File: azure-pipelines.yml
resources:
  repositories:
    - repository: AzureTemplates # In a different organization
      #endpoint: pwc-us-adv-digital
      type: git
      name: InfraDevOps/ado-templates
      ref: refs/heads/feature/leap

variables:
  - template: 'ado-vars.yml'
  - group: 'leap-common'
  - group: 'LEAP Common Configs'

pool:
  name: 'dds-concourse-ubuntu2004-01'
 # vmImage: ubuntu-latest
  workspace:
    clean: all

trigger:
  batch: true
  branches:
    include:
      - develop

  paths:
    exclude:
    - mfe-azure-pipelines.yml
    - blackduck-pipeline.yml
    
stages:
  - template: templates/main/pipeline.yml@AzureTemplates
    parameters:
      APP_DIR: ''
      NPMRC_CLEAR: ''
      NPMRC_CREATE: ''
